export const GET_MFI_API_REQUEST = 'GET_MFI_API_REQUEST';
export const GET_MFI_API_SUCCESS = 'GET_MFI_API_SUCCESS';
export const GET_MFI_API_FAIL = 'GET_MFI_API_FAIL';

export const GET_MFI_API_DETAIL_REQUEST = 'GET_MFI_API_DETAIL_REQUEST';
export const GET_MFI_API_DETAIL_SUCCESS = 'GET_MFI_API_DETAIL_SUCCESS';
export const GET_MFI_API_DETAIL_FAIL = 'GET_MFI_API_DETAIL_FAIL';

export const CREATE_MFI_API_REQUEST = 'CREATE_MFI_API_REQUEST';
export const CREATE_MFI_API_SUCCESS = 'CREATE_MFI_API_SUCCESS';
export const CREATE_MFI_API_FAIL = 'CREATE_MFI_API_FAIL';

export const DELETE_MFI_API_REQUEST = 'DELETE_MFI_API_REQUEST';
export const DELETE_MFI_API_SUCCESS = 'DELETE_MFI_API_SUCCESS';
export const DELETE_MFI_API_FAIL = 'DELETE_MFI_API_FAIL';

export const EDIT_MFI_API_REQUEST = 'EDIT_MFI_API_REQUEST';
export const EDIT_MFI_API_SUCCESS = 'EDIT_MFI_API_SUCCESS';
export const EDIT_MFI_API_FAIL = 'EDIT_MFI_API_FAIL';

export const REQUEST_MFI_API_REQUEST = 'REQUEST_MFI_API_REQUEST';
export const REQUEST_MFI_API_SUCCESS = 'REQUEST_MFI_API_SUCCESS';
export const REQUEST_MFI_API_FAIL = 'REQUEST_MFI_API_FAIL';

export const REMOVE_MFI_API_REQUEST = 'REMOVE_MFI_API_REQUEST'

