export const GET_USER_DEVICE_REQUEST = 'GET_USER_DEVICE_REQUEST';
export const GET_USER_DEVICE_SUCCESS = 'GET_USER_DEVICE_SUCCESS';
export const GET_USER_DEVICE_FAIL = 'GET_USER_DEVICE_FAIL';

export const GET_DEVICE_DETAIL_REQUEST = 'GET_DEVICE_DETAIL_REQUEST';
export const GET_DEVICE_DETAIL_SUCCESS = 'GET_DEVICE_DETAIL_SUCCESS';
export const GET_DEVICE_DETAIL_FAIL = 'GET_DEVICE_DETAIL_FAIL';

export const CREATE_DEVICE_REQUEST = 'CREATE_DEVICE_REQUEST';
export const CREATE_DEVICE_SUCCESS = 'CREATE_DEVICE_SUCCESS';
export const CREATE_DEVICE_FAIL = 'CREATE_DEVICE_FAIL';

export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';

export const GET_BRANDS_REQUEST = 'GET_BRANDS_REQUEST';
export const GET_BRANDS_SUCCESS = 'GET_BRANDS_SUCCESS';
export const GET_BRANDS_FAIL = 'GET_BRANDS_FAIL';

export const GET_STATUS_REQUEST = 'GET_STATUS_REQUEST';
export const GET_STATUS_SUCCESS = 'GET_STATUS_SUCCESS';
export const GET_STATUS_FAIL = 'GET_STATUS_FAIL';
