export const GET_MFI_TOKEN_REQUEST = 'GET_MFI_TOKEN_REQUEST';
export const GET_MFI_TOKEN_SUCCESS = 'GET_MFI_TOKEN_SUCCESS';
export const GET_MFI_TOKEN_FAIL = 'GET_MFI_TOKEN_FAIL';

export const GET_MFI_TOKEN_DETAIL_REQUEST = 'GET_MFI_TOKEN_DETAIL_REQUEST';
export const GET_MFI_TOKEN_DETAIL_SUCCESS = 'GET_MFI_TOKEN_DETAIL_SUCCESS';
export const GET_MFI_TOKEN_DETAIL_FAIL = 'GET_MFI_TOKEN_DETAIL_FAIL';

export const CREATE_MFI_TOKEN_REQUEST = 'CREATE_MFI_TOKEN_REQUEST';
export const CREATE_MFI_TOKEN_SUCCESS = 'CREATE_MFI_TOKEN_SUCCESS';
export const CREATE_MFI_TOKEN_FAIL = 'CREATE_MFI_TOKEN_FAIL';

export const DELETE_MFI_TOKEN_REQUEST = 'DELETE_MFI_TOKEN_REQUEST';
export const DELETE_MFI_TOKEN_SUCCESS = 'DELETE_MFI_TOKEN_SUCCESS';
export const DELETE_MFI_TOKEN_FAIL = 'DELETE_MFI_TOKEN_FAIL';

export const EDIT_MFI_TOKEN_REQUEST = 'EDIT_MFI_TOKEN_REQUEST';
export const EDIT_MFI_TOKEN_SUCCESS = 'EDIT_MFI_TOKEN_SUCCESS';
export const EDIT_MFI_TOKEN_FAIL = 'EDIT_MFI_TOKEN_FAIL';

