export const GET_CERTIFICATE_REQUEST = 'GET_CERTIFICATE_REQUEST';
export const GET_CERTIFICATE_SUCCESS = 'GET_CERTIFICATE_SUCCESS';
export const GET_CERTIFICATE_FAIL = 'GET_CERTIFICATE_FAIL';

export const GET_CERTIFICATE_DETAIL_REQUEST = 'GET_CERTIFICATE_DETAIL_REQUEST';
export const GET_CERTIFICATE_DETAIL_SUCCESS = 'GET_CERTIFICATE_DETAIL_SUCCESS';
export const GET_CERTIFICATE_DETAIL_FAIL = 'GET_CERTIFICATE_DETAIL_FAIL';

export const CREATE_CERTIFICATE_REQUEST = 'CREATE_CERTIFICATE_REQUEST';
export const CREATE_CERTIFICATE_SUCCESS = 'CREATE_CERTIFICATE_SUCCESS';
export const CREATE_CERTIFICATE_FAIL = 'CREATE_CERTIFICATE_FAIL';

export const DELETE_CERTIFICATE_REQUEST = 'DELETE_CERTIFICATE_REQUEST';
export const DELETE_CERTIFICATE_SUCCESS = 'DELETE_CERTIFICATE_SUCCESS';
export const DELETE_CERTIFICATE_FAIL = 'DELETE_CERTIFICATE_FAIL';

export const EDIT_CERTIFICATE_REQUEST = 'EDIT_CERTIFICATE_REQUEST';
export const EDIT_CERTIFICATE_SUCCESS = 'EDIT_CERTIFICATE_SUCCESS';
export const EDIT_CERTIFICATE_FAIL = 'EDIT_CERTIFICATE_FAIL';

export const CLOSE_DIALOG_CERTIFICATE = 'CLOSE_DIALOG_CERTIFICATE';
