export const GET_ACCESSORY_INFO_REQUEST = 'GET_ACCESSORY_INFO_REQUEST';
export const GET_ACCESSORY_INFO_SUCCESS = 'GET_ACCESSORY_INFO_SUCCESS';
export const GET_ACCESSORY_INFO_FAIL = 'GET_ACCESSORY_INFO_FAIL';

export const CREATE_ACCESSORY_INFO_REQUEST = 'CREATE_ACCESSORY_INFO_REQUEST';
export const CREATE_ACCESSORY_INFO_SUCCESS = 'CREATE_ACCESSORY_INFO_SUCCESS';
export const CREATE_ACCESSORY_INFO_FAIL = 'CREATE_ACCESSORY_INFO_FAIL';
