export const GET_ORGANIZATION_REQUEST = 'GET_ORGANIZATION_REQUEST';
export const GET_ORGANIZATION_SUCCESS = 'GET_ORGANIZATION_SUCCESS';
export const GET_ORGANIZATION_FAIL = 'GET_ORGANIZATION_FAIL';

export const CREATE_ORGANIZATION_REQUEST = 'CREATE_ORGANIZATION_REQUEST';
export const CREATE_ORGANIZATION_SUCCESS = 'CREATE_ORGANIZATION_SUCCESS';
export const CREATE_ORGANIZATION_FAIL = 'CREATE_ORGANIZATION_FAIL';

export const SWITCH_ORGANIZATION_REQUEST = 'SWITCH_ORGANIZATION_REQUEST';
export const SWITCH_ORGANIZATION_SUCCESS = 'SWITCH_ORGANIZATION_SUCCESS';
export const SWITCH_ORGANIZATION_FAIL = 'SWITCH_ORGANIZATION_FAIL';

export const GET_ORGANIZATION_MEMBER_REQUEST = 'GET_ORGANIZATION_MEMBER_REQUEST';
export const GET_ORGANIZATION_MEMBER_SUCCESS = 'GET_ORGANIZATION_MEMBER_SUCCESS';
export const GET_ORGANIZATION_MEMBER_FAIL = 'GET_ORGANIZATION_MEMBER_FAIL';

export const GET_ROLE_ORGANIZATION_MEMBER_REQUEST = 'GET_ROLE_ORGANIZATION_MEMBER_REQUEST';
export const GET_ROLE_ORGANIZATION_MEMBER_SUCCESS = 'GET_ROLE_ORGANIZATION_MEMBER_SUCCESS';
export const GET_ROLE_ORGANIZATION_MEMBER_FAIL = 'GET_ROLE_ORGANIZATION_MEMBER_FAIL';

export const INVITE_ORGANIZATION_MEMBER_REQUEST = 'INVITE_ORGANIZATION_MEMBER_REQUEST';
export const INVITE_ORGANIZATION_MEMBER_SUCCESS = 'INVITE_ORGANIZATION_MEMBER_SUCCESS';
export const INVITE_ORGANIZATION_MEMBER_FAIL = 'INVITE_ORGANIZATION_MEMBER_FAIL';

export const GET_DETAIL_ORGANIZATION_MEMBER_REQUEST = 'GET_DETAIL_ORGANIZATION_MEMBER_REQUEST';
export const GET_DETAIL_ORGANIZATION_MEMBER_SUCCESS = 'GET_DETAIL_ORGANIZATION_MEMBER_SUCCESS';
export const GET_DETAIL_ORGANIZATION_MEMBER_FAIL = 'GET_DETAIL_ORGANIZATION_MEMBER_FAIL';

export const DELETE_MEMBER_ORGANIZATION_REQUEST = 'DELETE_MEMBER_ORGANIZATION_REQUEST';
export const DELETE_MEMBER_ORGANIZATION_SUCCESS = 'DELETE_MEMBER_ORGANIZATION_SUCCESS';
export const DELETE_MEMBER_ORGANIZATION_FAIL = 'DELETE_MEMBER_ORGANIZATION_FAIL';

export const UPDATE_MEMBER_ORGANIZATION_REQUEST = 'UPDATE_MEMBER_ORGANIZATION_REQUEST';
export const UPDATE_MEMBER_ORGANIZATION_SUCCESS = 'UPDATE_MEMBER_ORGANIZATION_SUCCESS';
export const UPDATE_MEMBER_ORGANIZATION_FAIL = 'UPDATE_MEMBER_ORGANIZATION_FAIL';

export const GET_PERMISSION_REQUEST = 'GET_PERMISSION_REQUEST';
export const GET_PERMISSION_SUCCESS = 'GET_PERMISSION_SUCCESS';
export const GET_PERMISSION_FAIL = 'GET_PERMISSION_FAIL';
