export const GET_ORGANIZATION_REQUEST = 'GET_ORGANIZATION_REQUEST';
export const GET_ORGANIZATION_SUCCESS = 'GET_ORGANIZATION_SUCCESS';
export const GET_ORGANIZATION_FAIL = 'GET_ORGANIZATION_FAIL';

export const CREATE_ORGANIZATION_REQUEST = 'CREATE_ORGANIZATION_REQUEST';
export const CREATE_ORGANIZATION_SUCCESS = 'CREATE_ORGANIZATION_SUCCESS';
export const CREATE_ORGANIZATION_FAIL = 'CREATE_ORGANIZATION_FAIL';

export const SWITCH_ORGANIZATION_REQUEST = 'SWITCH_ORGANIZATION_REQUEST';
export const SWITCH_ORGANIZATION_SUCCESS = 'SWITCH_ORGANIZATION_SUCCESS';
export const SWITCH_ORGANIZATION_FAIL = 'SWITCH_ORGANIZATION_FAIL';

export const GET_ORGANIZATION_MEMBER_REQUEST = 'GET_ORGANIZATION_MEMBER_REQUEST';
export const GET_ORGANIZATION_MEMBER_SUCCESS = 'GET_ORGANIZATION_MEMBER_SUCCESS';
export const GET_ORGANIZATION_MEMBER_FAIL = 'GET_ORGANIZATION_MEMBER_FAIL';

export const GET_ROLE_ORGANIZATION_MEMBER_REQUEST = 'GET_ROLE_ORGANIZATION_MEMBER_REQUEST';
export const GET_ROLE_ORGANIZATION_MEMBER_SUCCESS = 'GET_ROLE_ORGANIZATION_MEMBER_SUCCESS';
export const GET_ROLE_ORGANIZATION_MEMBER_FAIL = 'GET_ROLE_ORGANIZATION_MEMBER_FAIL';
