export const GET_BRAND_REQUEST = 'GET_BRAND_REQUEST';
export const GET_BRAND_SUCCESS = 'GET_BRAND_SUCCESS';
export const GET_BRAND_FAIL = 'GET_BRAND_FAIL';

export const GET_BRAND_DETAIL_REQUEST = 'GET_BRAND_DETAIL_REQUEST';
export const GET_BRAND_DETAIL_SUCCESS = 'GET_BRAND_DETAIL_SUCCESS';
export const GET_BRAND_DETAIL_FAIL = 'GET_BRAND_DETAIL_FAIL';

export const CREATE_BRAND_REQUEST = 'CREATE_BRAND_REQUEST';
export const CREATE_BRAND_SUCCESS = 'CREATE_BRAND_SUCCESS';
export const CREATE_BRAND_FAIL = 'CREATE_BRAND_FAIL';

export const DELETE_BRAND_REQUEST = 'DELETE_BRAND_REQUEST';
export const DELETE_BRAND_SUCCESS = 'DELETE_BRAND_SUCCESS';
export const DELETE_BRAND_FAIL = 'DELETE_BRAND_FAIL';

export const EDIT_BRAND_REQUEST = 'EDIT_BRAND_REQUEST';
export const EDIT_BRAND_SUCCESS = 'EDIT_BRAND_SUCCESS';
export const EDIT_BRAND_FAIL = 'EDIT_BRAND_FAIL';

